nim_api_agency_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: nim.controller.agency:indexAction
        _sylius:
            paginate: $limit
            sortable: $sorting
            filterable: $criteria

nim_api_agency_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.agency:createAction

nim_api_agency_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.agency:updateAction

nim_api_agency_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: nim.controller.agency:showAction

nim_api_agency_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: nim.controller.agency:deleteAction

