nim_api_mission_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: nim.controller.mission:indexAction
        _sylius:
            paginate: $limit
            sortable: $sorting
            filterable: $criteria

nim_api_mission_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.mission:createAction

nim_api_mission_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.mission:updateAction

nim_api_mission_show:
    pattern: /{id}
    methods: [GET]
    defaults:
#        _format: json
        _controller: nim.controller.mission:showAction

nim_api_mission_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: nim.controller.mission:deleteAction
